### ISSUE TITLE
Please provide an example configuration on how this would work with Docker

### ISSUE THREAD

**Issue by trajano** [openzipkin/zipkin-dependencies#168]
I tried the following but failed.

```yaml
services:
  zipkin:
    image: openzipkin/zipkin:2.21.1
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://elasticsearch:9200
    networks:
      - management
      - management-ui
      - default
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
  zipkin-dependencies:
    image: openzipkin/zipkin-dependencies:2.4.1
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://elasticsearch:9200
    deploy:
      resources:
        limits:
          cpus: '0.5'
 ```

 Exception in thread "main" org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[10.0.0.4:9200]]
